services:
  api:
    build: .
    # ports:
    #   - "8000:8000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.energypebble.rule=Host(`energypebble.tdlx.nl`)"  
      - "traefik.http.routers.energypebble.entrypoints=websecure" # use websecure for HTTPS traffic
      - "traefik.http.routers.energypebble.tls.certresolver=myresolver"
      - "traefik.http.services.energypebble.loadbalancer.server.port=8000" # specify the port of the service
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
      
