---
# Authelia configuration for Energy Pebble

# Server configuration
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: 6s
    write: 6s
    idle: 30s

# Logging configuration
log:
  level: info
  format: text
  file_path: ""
  keep_stdout: true

# Theme configuration
theme: light

# JWT secret for password reset tokens
jwt_secret: a_very_important_secret

# Default redirection URL
default_redirection_url: https://energypebble.tdlx.nl

# TOTP configuration
totp:
  disable: true
  issuer: energypebble.tdlx.nl
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

# Webauthn configuration
webauthn:
  disable: true

# Duo Push API configuration
duo_api:
  disable: true

# Authentication backend configuration
authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 5m
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 3
      key_length: 32
      salt_length: 16
      memory: 65536
      parallelism: 4

# Access control configuration
access_control:
  default_policy: deny
  rules:
    # Allow access to the public API endpoints
    - domain: energypebble.tdlx.nl
      policy: bypass
      resources:
        - "^/api/.*$"
        - "^/$"
        - "^/energy-pebble-image.jpg$"
    
    # Require authentication for the dashboard
    - domain: energypebble.tdlx.nl
      policy: one_factor
      resources:
        - "^/dashboard$"
    
    # Allow access to auth endpoints
    - domain: energypebble.tdlx.nl
      policy: bypass
      resources:
        - "^/api/verify$"
        - "^/api/authz/.*$"

# Session configuration
session:
  name: authelia_session
  domain: energypebble.tdlx.nl
  same_site: lax
  secret: unsecure_session_secret
  max_age: 1h
  inactivity: 5m
  remember_me_duration: 1M

# Storage configuration
storage:
  local:
    path: /config/db.sqlite3
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this

# Notifier configuration (disabled for now)
notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt

# Regulation configuration
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300