---
# Authelia configuration for Energy Pebble (v4.38+ compatible)

# Server configuration (new format)
server:
  address: 'tcp://0.0.0.0:9091'
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: 6s
    write: 6s
    idle: 30s

# Logging configuration
log:
  level: info
  format: text
  file_path: ""
  keep_stdout: true

# Theme configuration
theme: light

# TOTP configuration
totp:
  disable: true
  issuer: energypebble.tdlx.nl
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

# Webauthn configuration
webauthn:
  disable: true

# Duo Push API configuration
duo_api:
  disable: true

# Authentication backend configuration
authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 5m
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 3
      key_length: 32
      salt_length: 16
      memory: 65536
      parallelism: 4

# Access control configuration
access_control:
  default_policy: deny
  rules:
    # Allow access to public API endpoints and main page
    - domain: energypebble.tdlx.nl
      policy: bypass
      resources:
        - "^/api/color-code.*$"
        - "^/api/json.*$"
        - "^/api/sample.*$"
        - "^/docs.*$"
        - "^/openapi.json$"
        - "^/$"
        - "^/energy-pebble-image.jpg$"
        - "^/components.css$"
    
    # Require authentication for protected API endpoints
    - domain: energypebble.tdlx.nl
      policy: one_factor
      resources:
        - "^/api/verify.*$"
        - "^/api/user.*$"
        - "^/api/admin.*$"
        - "^/api/firmware.*$"
    
    # Require authentication for the dashboard and impact circle
    - domain: energypebble.tdlx.nl
      policy: one_factor
      resources:
        - "^/dashboard.*$"
        - "^/impact-circle.*$"
    
    # Require authentication for admin area  
    - domain: energypebble.tdlx.nl
      policy: one_factor
      resources:
        - "^/admin.*$"

# Session configuration (new format)
session:
  cookies:
    - name: authelia_session
      domain: tdlx.nl
      authelia_url: https://auth.tdlx.nl/
      default_redirection_url: https://energypebble.tdlx.nl/dashboard
      same_site: lax
      inactivity: 5m
      expiration: 1h
      remember_me: 1M
  # secret loaded from environment variable

# Storage configuration
storage:
  local:
    path: /config/db.sqlite3
  # encryption_key loaded from environment variable

# Notifier configuration (disabled for now)
notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt

# Regulation configuration
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300