users:
  thomas:
    displayname: "Thomas"
    password: "$argon2id$v=19$m=65536,t=3,p=4$kEPkP0C77Ti9zO0ORfVVlA$Skd5xk6Gt/9lNTyM10y4N8vXxWLCxo4zzNGwzjYAj2Y"
    email: "thomas@energypebble.local"
    groups:
      - admins
      - users
  seba:
    displayname: "Seba"
    password: "$argon2id$v=19$m=65536,t=3,p=4$1F8LHH1opYQ3FWWwzTmaRw$YI+2nZkx4JIcrgE4QgFlMFxknK/Eaht/EYYQZeK10Tk"
    email: "seba@energypebble.local"
    groups:
      - users