users:
  thomas:
    displayname: "Thomas"
    password: "$argon2id$v=19$m=65536,t=3,p=4$kEPkP0C77Ti9zO0ORfVVlA$Skd5xk6Gt/9lNTyM10y4N8vXxWLCxo4zzNGwzjYAj2Y"
    email: "thomas@energypebble.local"
    groups:
      - admins
      - users
  seba:
    displayname: "Seba"
    password: "$argon2id$v=19$m=65536,t=3,p=4$1F8LHH1opYQ3FWWwzTmaRw$YI+2nZkx4JIcrgE4QgFlMFxknK/Eaht/EYYQZeK10Tk"
    email: "seba@energypebble.local"
    groups:
      - users    
  willie:
    displayname: "Willie"
    password: "$argon2id$v=19$m=65536,t=3,p=4$EKQrOdPhZGOJdfF0fl2ktg$vyn8gTWO0Gu7x+HawfXHG3oq/5LGhGeCWOxHORMJq10"
    email: "willie@energypebble.local"
    groups:
      - users

  herman:
    displayname: "Herman"
    password: "$argon2id$v=19$m=65536,t=3,p=4$9iiTAXkF3gDyfS6gp9s8jA$yEWnbzz6JUjE2xKN/6mI6TxXmMvTqc5vXuI2BNQdIrI"                 
    email: "herman@energypebble.local"
    groups:
      - users

  frederic:
    displayname: "Frederic"
    password: "$argon2id$v=19$m=65536,t=3,p=4$RUSrHKrnPpEaa+3vM3Yk/Q$OVphlYuShkyJT7neigCJqlO70hMVQR83KANupX/Ajj8"
    email: "frederic@energypebble.local"
    groups:
      - users

  edumarcu:
    displayname: "Edumarcu"
    password: "$argon2id$v=19$m=65536,t=3,p=4$30oB+bZwCvhH52czvD2UcQ$HNLY1jV7XbeXdsNmWhi7bh0EMcenxuN9VfFcR0T1nM0"
    email: "edumarcu@energypebble.local"
    groups:
      - admins
      - users

